export const PRODUCTS = [
  {
    id: 1,
    name: "Rebirth  Sleeveless",
    price: 200,
    images: ["../images/product1.png", "../images/product2.png"],
    sizes: ["Large Cut"],
    soldOut: false,
  },

  {
    id: 2,
    name: "Black Rebirth Sleeveless",
    price: 200,
    images: ["../images/product3.png", "../images/product4.png"],
    sizes: ["Large Cut"],
    soldOut: false,
  },

  {
    id: 3,
    name: "Cosmic Rebirth Tee",
    price: 200,
    images: ["../images/product5.png", "../images/product6.png"],
    sizes: ["M", "L", "XL"],
    soldOut: false,
  },
  //   {
  //     id: 5,
  //     name: "Classic Plain Tee",
  //     price: 200,
  //     images: [],
  //     sizes: ["M", "L", "XL"],
  //     soldOut: false,
  //   },
  {
    id: 4,
    name: "Cosmic Black Tee",
    price: 200,
    images: ["../images/product7.png", "../images/product8.png"],
    sizes: ["M", "L", "XL"],
    soldOut: false,
  },
  //   {
  //     id: 7,
  //     name: "Classic Black Tee",
  //     price: 200,
  //     images: [],
  //     sizes: ["M", "L", "XL"],
  //     soldOut: false,
  //   },
  {
    id: 5,
    name: "Rebirth Bucket-hat",
    price: 200,
    images: ["../images/product9.png"],
    soldOut: false,
  },
  {
    id: 6,
    name: "Rebirth Beanie",
    price: 200,
    images: ["../images/product10.png"],
    soldOut: true,
  },
  {
    id: 7,
    name: "Rebirth Croptop",
    price: 200,
    images: ["../images/13.png", "../images/14.png"],
    soldOut: false,
  },
  {
    id: 8,
    name: "Rebirth Croptop Black",
    price: 200,
    images: ["../images/11.png", "../images/12.png"],
    soldOut: false,
  },
];

export const statesInNigeria = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const regions = [
  "Nigeria",
  "United States",
  "Canada",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "Norway",
  "Sweden",
  "Denmark",
  "Finland",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Ireland",
  "Luxembourg",
  "Portugal",
  "Greece",
  "Iceland",
  "Singapore",
  "Israel",
  "Slovenia",
  "Estonia",
  "Czech Republic",
  "Slovakia",
  "Lithuania",
  "Latvia",
  "Poland",
  "Hungary",
  "Croatia",
  "Malta",
  "Cyprus",
  "Bulgaria",
  "Romania",
  "Russia",
];
