export const PRODUCTS = [
  {
    id: 1,
    name: "Rebirth  Sleeveless",
    price: "$200",
    image: "../images/product1.png",
    sizes: ["Large Cut"],
    soldOut: false,
  },
  {
    id: 2,
    name: "Rebirth Summer Sleeveless",
    price: "$200",
    image: "../images/product2.png",
    sizes: ["Large Cut"],
    soldOut: true,
  },
  {
    id: 3,
    name: "Black Rebirth Sleeveless",
    price: "$200",
    image: "../images/product3.png",
    sizes: ["Large Cut"],
    soldOut: false,
  },
  {
    id: 4,
    name: "Black Summer Rebirth Sleeveless",
    price: "$200",
    image: "../images/product4.png",
    sizes: ["Large Cut"],
    soldOut: false,
  },
  {
    id: 5,
    name: "Cosmic Rebirth Tee",
    price: "$200",
    image: "../images/product5.png",
    sizes: ["M", "L", "XL"],
    soldOut: false,
  },
  {
    id: 6,
    name: "Classic Plain Tee",
    price: "$200",
    image: "../images/product6.png",
    sizes: ["M", "L", "XL"],
    soldOut: false,
  },
  {
    id: 7,
    name: "Cosmic Black Tee",
    price: "$200",
    image: "../images/product7.png",
    sizes: ["M", "L", "XL"],
    soldOut: false,
  },
  {
    id: 8,
    name: "Classic Black Tee",
    price: "$200",
    image: "../images/product8.png",
    sizes: ["M", "L", "XL"],
    soldOut: false,
  },
  {
    id: 9,
    name: "Rebirth Bucket-hat",
    price: "$200",
    image: "../images/product9.png",
    soldOut: false,
  },
  {
    id: 10,
    name: "Rebirth Beanie",
    price: "$200",
    image: "../images/product10.png",
    soldOut: true,
  },
];
